---
title: "EDA buscas"
output: html_notebook
---

O objeto principal da análise são as buscas e a navegação depois da busca. Criamos esses dados a partir dos dados originais da wikimedia em `/data/search_data.csv`. 

Aqui, exploramos esses dados. 

```{r setup}
library(tidyverse)
library(here)
library(lubridate)
theme_set(theme_bw())
```

```{r ETL}
buscas = read_csv(here::here("data/search_data.csv"))

```
```{r}
clickthrough <- buscas %>% group_by(day = date(session_start_date),session = session_id, group) %>%     summarise(clicks = sum(num_clicks)) %>% 
    group_by(day, group) %>% 
    summarise(clickthrough_rate = sum(clicks > 0)/n()) 

zero_results <- buscas %>% group_by(day = date(session_start_date)) %>% 
    group_by(day, group) %>% 
    summarise(zero_results = sum(results == 0)/n())

try_results <- buscas %>% group_by(day = date(session_start_date)) %>% 
    group_by(day, group) %>% 
    summarise(try_results = round(mean(na.exclude(first_click))))

session_size <- buscas %>% group_by(day = date(session_start_date)) %>% 
    group_by(day, group) %>% 





```


